joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

position_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  state_publish_rate: 50
  action_monitor_rate: 20
  joints:
    - arm_turntable_bicep_joint
    - arm_bicep_forearm_joint
    - arm_forearm_wrist_joint
    - arm_wrist_claw_joint
